# Generated by Django 5.0 on 2024-01-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="fullName",
            field=models.CharField(default="N", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="profileType",
            field=models.CharField(
                choices=[
                    ("Paciente", "Paciente"),
                    ("Profissional da Saúde", "Profissional da Saúde"),
                ],
                default="N",
                max_length=50,
            ),
        ),
    ]
