"""empty message

Revision ID: 22af1726be9f
Revises: 8e5db34e92a7
Create Date: 2024-04-07 20:56:12.185784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22af1726be9f'
down_revision = '8e5db34e92a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
