"""empty message

Revision ID: f6aa0f16285f
Revises: 14b3bd62dd68
Create Date: 2024-04-07 20:41:14.581654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aa0f16285f'
down_revision = '14b3bd62dd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('pending_request_model', schema=None) as batch_op:
        batch_op.drop_constraint('pending_request_model_professional_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('pending_request_model_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['professional_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'health_professionals', ['patient_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_request_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pending_request_model_patient_id_fkey', 'users', ['patient_id'], ['id'])
        batch_op.create_foreign_key('pending_request_model_professional_id_fkey', 'users', ['professional_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
